routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::resource('shops', 'ShopController');
Route::post('shops/{id}/set-active', 'ShopController@setActiveStatus');
Route::post('shops/sort-images/', 'ShopController@sortImages');
Route::get('shops/{id}/products', 'ShopController@showProducts');

Route::resource('shop-images', 'ShopImageController');
Route::get('shop-images/shop/{id}', 'ShopImageController@showByShop');
Route::get('shops/{id}/set-image', 'ShopController@setImageAfterCreate');
Route::get('shops/check-images/{id}', 'ShopController@checkIfHaveImages');

Route::resource('words', 'WordController');

Route::resource('users', 'UserController');

Route::post('categories/sort-images/', 'CategoryController@sortImages');
Route::resource('categories', 'CategoryController');

Route::resource('category-images', 'CategoryImageController');
Route::get('category-images/category/{id}', 'CategoryImageController@showByCategory');

Route::resource('products', 'ProductController');
Route::post('products/sort-images', 'ProductController@sortImages');
Route::get('products/{id}/set-image', 'ProductController@setImageAfterCreate');
Route::get('products/check-images/{id}', 'ProductController@checkIfHaveImages');
Route::post('products/{id}/set-active', 'ProductController@setActiveStatus');

Route::resource('product-images', 'ProductImageController');
Route::get('product-images/product/{id}', 'ProductImageController@showByProduct');

Route::post('product-offers/calculate', 'ProductOfferController@calculate');

Route::resource('messages', 'MessageController');
Route::get('send-to-ios', 'MessageController@sendIOS');
Route::post('messages/send/{id}', 'MessageController@send');

Route::resource('beacons', 'ShopBeaconController');
Route::get('beacon/generate', 'ShopBeaconController@generateSerial');

Route::resource('products-beacon', 'ProductBeaconController');

Route::get('province/localities/{id}','ProvinceController@showLocalities');

Route::get('public_content', 'ContentController@public');
Route::get('content', 'ContentController@index');
Route::post('content', 'ContentController@store');


Route::get('help', 'HelpController@index');
Route::post('help', 'HelpController@store');

Route::resource('clients', 'ClientController');

Route::get('banners', 'BannerController@index');
Route::post('banners','BannerController@store');
Route::put('banners', 'BannerController@update');

Route::get('payments', 'PaymentController@index');
Route::get('payments/{id}', 'PaymentController@show');
Route::put('payments/{id}', 'PaymentController@update');

Route::post('mp/notifications', 'MPController@notifications');
//Route::post('mp/notifications', 'MPController@notifications');

Route::get('statistics', 'StatisticsController@index');
Route::get('statistics/{id}', 'StatisticsController@index');

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Formatters\Api\ShopFormatter;
use Illuminate\Database\Eloquent\SoftDeletes;
use Storage;
use File;
use Image;
use App\Helpers\ImagesResize;
use Illuminate\Support\Facades\DB;

class Shop extends Model
{
    use ShopFormatter;
    use SoftDeletes;
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'shops';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'cuit',
        'name',
        'business_name',
        'description',
        'active',
        'phone',
        'lat',
        'lng',
        'address',
        'mp_key',
        'mp_client_id',
        'mp_client_secret',
        'email',
        'vip',
        'iva',
        'iibb',
        'schedule',
        'observation',
        'contact_management',
        'logo',
        'locality_id',
        'province_id',
        'created_by'
    ];
    
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    
    /**
     * Hidden fields
     */
    protected $hidden = ['created_at', 'updated_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany('App\Models\User', 'pivot_user_shops', 'shop_id', 'user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products()
    {
        return $this->hasMany('App\Models\Product');
    }

    public function payments()
    {
        return $this->hasMany('App\Models\Payment');
    }

    public function points()
    {
        return $this->hasMany('App\Models\UserPoint');
    }
    
    public function califications()
    {
        return $this->hasMany('App\Models\Califications');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany('App\Models\ShopImage', 'shop_id', 'id')->orderBy('order');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function beacons()
    {
        return $this->hasMany('App\Models\ShopBeacon');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator()
    {
        return $this->belongsTo('App\Models\User', 'created_by', 'id');
    }

    /**
     * Update Shop in the database.
     *
     * @param  array $attributes
     * @param  array $options
     * @return bool
     */
    public function update(array $attributes = [], array $options = [])
    {
        $attributes['users'] = (array_key_exists('users', $attributes)) ? $attributes['users'] : [];
        $attributes['words'] = (array_key_exists('words', $attributes)) ? $attributes['words'] : [];
        $attributes['active'] = (array_key_exists('active', $attributes)) ? (bool) $attributes['active'] : false;
        $attributes['vip'] = (array_key_exists('vip', $attributes)) ? (bool) $attributes['vip'] : false;

        $this->fill($attributes)->save();

        if(array_key_exists ( 'logo',  $attributes )){
            $this->logo = 'storage/' .env('STORAGE_SHOP_IMAGES') . '/' . $this->id.'_logo.png';
            $this->saveLogo($attributes['logo']);
        }

        if (in_array(Auth::user()->type,['administrator','seller']))
        {
            $this->updateUsers($attributes['users']);
        }

        // Un negocio no debe poder pasarse a estado activo si no completó la Key de Mercado Pago 
        /*if( !$this->mp_client_id || !$this->mp_client_secret){
            $this->active = false;
            $this->save();
        }*/
    }

    /**
     * Update Logo in Shop
     *
     */
    private function saveLogo($image)
    {
        $image_name =  $this->id.'_logo.png';
        Storage::put( '/public/' .env('STORAGE_SHOP_IMAGES') . '/' . $image_name ,File::get($image) );

        $path = public_path().'/..'.'/storage/app/'. '/public/' . env('STORAGE_SHOP_IMAGES') . '/';
        
        ImagesResize::maxSize($path,$image_name,100,100);
    }

    /**
     * Update Users in Shop
     *
     * @param array $users
     */
    private function updateUsers(array $users = [])
    {
        $this->users()->detach();
        $this->users()->attach($users);
        $this->save();
    }    

    /**
     * Sólo tiendas activas.
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeActive($query)
    {
        return $query->where('active', 1);
    }

    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder $query
     */
    //Scope para traer facilmente solo a los que tenemos acceso
    public function scopeAccesible($query)
    {
        $user = Auth::user();

        switch($user->type)
        {
            case 'administrator': //El admin ve everything
                return $query;

            case 'operator': //El operador solo puede ver los shops que puede administrar

                return $query->whereHas('users', function($subQuery) use ($user){
                        $subQuery->where('users.id', $user->id);
                    });

            case 'seller': //El vendedor solo ve los shops que creo el mismo

                return $query->whereHas('creator', function($subQuery) use ($user){
                    $subQuery->where('users.id', $user->id);
                });
        }

        throw new \Exception('El usuario no tiene acceso a shops');
    }

    /**
    * Get CUIT Formated
    *
    * @return string
    */
    public function getCuitFormatedAttribute()
    {
        if($this->cuit == '')
            return '';
        //  Formato ##-########-#
        return  substr($this->cuit, 0,2).'-'.substr($this->cuit, 2,8).'-'.substr($this->cuit, 10,1);
    }

    public function getIibbAttribute($value)
    {
        return ($value > 0) ? $value : '';
    }
    
    public static function getShopsByBeacon( $beacons, array $options ){
        
        $shopBeaconModel = ShopBeacon::with('shop')
                ->has('shop');

        foreach( $beacons as $key => $b ){

            $serial = $b->major . "/" . $b->minor;
            
            if(!$key)
                $shopBeaconModel->where('serial', $serial);
            
            $shopBeaconModel->orWhere('serial', $serial);

        }
        
        if(isset($options["limit"]))
            $shopBeaconModel->limit($options["limit"]);
        
        $shops = $shopBeaconModel->get()->toArray();        
        
        if(!empty($options["add_distances"]))
            $shops = self::addDistances ($shops, $beacons);


        return $shops;
        
    }
    
    public static function addDistances(array $shops, array $beacons){
        
        foreach($shops as &$s){
            
            $shopBeaconSerial = $s["serial"];
            
            foreach($beacons as $b){
                
                $beaconSerial = $b->major . "/" . $b->minor;
                
                if($beaconSerial == $shopBeaconSerial){
                    $s["distance"] = $b->distance;
                }
               
            }          
            
        }
        
        return $shops;
        
    }
    
    public static function getShopsByCoordinates(array $select, $lat, $lng, $maxDistance){
        
        $fields = "";
        
        foreach($select as $key=>$s){
            if($key)
               $fields .= ",";
            
            $fields .= $s;
        }
        
        $shopDistanceQuery = 
        "SELECT {$fields},
            (p.distance_unit
             * DEGREES(ACOS(COS(RADIANS(p.latpoint))
             * COS(RADIANS(shop.lat))
             * COS(RADIANS(p.longpoint - shop.lng))
             + SIN(RADIANS(p.latpoint))
             * SIN(RADIANS(shop.lat))))) * 1000 AS distance
        FROM shops AS shop
        JOIN (
            SELECT  {$lat}  AS latpoint,  {$lng} AS longpoint,
            {$maxDistance} AS radius, 111.045 AS distance_unit
        ) AS p ON 1=1 WHERE shop.lat
        BETWEEN p.latpoint  - (p.radius / p.distance_unit)
            AND p.latpoint  + (p.radius / p.distance_unit)
       AND shop.lng
        BETWEEN p.longpoint - (p.radius / (p.distance_unit * COS(RADIANS(p.latpoint))))
            AND p.longpoint + (p.radius / (p.distance_unit * COS(RADIANS(p.latpoint))))
         AND shop.active = 1 ORDER BY distance";
            
        return DB::select( \DB::raw($shopDistanceQuery) );
        
    }

}

resources/views/shop/datatable.blade.php
<table class="table table-striped table-condensed" id="shops-datatable">
    <thead>
        <tr>
            <th class="text-center">{{ trans('data.id') }}</th>
            <th>{{ trans('data.name') }}</th>
            <th>{{ trans('data.cuit') }}</th>
            <th>{{ trans('data.phone') }}</th>
            <th>{{ trans('data.email') }}</th>
            <th>{{ trans('data.action') }}</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($shops as $shop)
            <tr @if(!$shop->active) class="desactive" @endif>
                <td class="text-center">{{ str_limit($shop->id,30) }}</td>
                <td><a href="{{ url('shops/'.$shop->id) }}">{{ str_limit($shop->name,30) }}</a></td>
                <td>{{ $shop->cuit_formated }}</td>
                <td>{{ str_limit($shop->phone,30) }}</td>
                <td>{{ str_limit($shop->email,30) }}</td>
                <td>
                    <form action='{{ url('shops/'.$shop->id) }}' method='POST' id="shop-delete-{{ $shop->id }}">
                        <input type="hidden" name="_method" value="DELETE">
                        {{ csrf_field()}}
                        <a class="icon mdi mdi-edit btn btn-primary" href="{{ url('shops/'.$shop->id) }}" data-toggle="tooltip" title="{{ trans("process.update") }}"></a>
                        @if(\Auth::user()->type == 'administrator')
                            <a data-modal="full-danger"  class="btn btn-danger md-trigger " onclick="formSelected='shop-delete-{{ $shop->id }}'" data-toggle="tooltip" title="{{ trans("process.delete") }}">
                                <span class="icon mdi mdi-delete"></span>
                            </a>
                        @endif
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

@section('footer')
    <script>
        $('#shops-datatable').DataTable({
            "pageLength": 100
        });
    </script>
@endsection

resources/views/shop/header.blade.php
@section('containt-title') {{ trans('models.shops') }} @endsection

@section('menu-marcas') class="active" @endsection

@section('breadcrumbs') 
    <li><a href="{{ url('shops') }}" >{{ trans('data.list',['model'=>trans('models.shops')] ) }}</a></li>
    @yield('shop-breadcrumbs')
@endsection

resources/views/shop/imageForm.blade.php
@extends('layouts.panel')

@section('content-panel')
    @include('shop.header')
    <div style="display:none;" class="tab-pane fade in active" id="shop-form">@include('shop.form')</div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
            <div role="alert" class="alert alert-primary alert-icon alert-icon-colored">
                <div class="icon"><span class="mdi mdi-info-outline"></span></div>
                <div class="message">
                    <strong>Seleccione las imágenes a mostrar de la portada de su negocio.</strong>
                    <ul>
                        <li>Formato: JPG o PNG</li>
                        <li>Tamaño mínimo: 800 x 400 px</li>
                        <li>Tamaño máximo: 1280 x 720 px</li>
                    </ul>
                </div>
            </div>
        </div>
        @include('shopimage.form')
        <div id="shopimage-list" class="col-xs-12">@include('shopimage.list_set')</div>
    </div>
    <br>
    <div class="row">
        <form action="{{ url('shops/'.$shop->id.'/set-active') }}" id="form_status" method="post">
            <div class="form-group col-md-2">
                <label for="status">Estado</label>
                <select class="form-control" id="status" name="active">
                    <option value="1">Activo</option>
                    <option value="0" selected>Inactivo</option>
                </select>
            </div>
            {{ csrf_field()}}
            <div class="col-md-2 col-md-offset-10">
                <button type="submit" class="btn btn-info">Finalizar</button>
            </div>
        </form>
    </div>

@endsection
@section('footer')
    @php /*<script src="{{ URL::asset('js/users/pattern-phone.js') }}" type="text/javascript"></script> */@endphp
    <script src="{{ URL::asset('js/imagesAjax.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/show.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/gmap.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/showLocalities.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/sortImages.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/setting_shop.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/products/selectWords.jquery.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/products/addWord.jquery.js') }}" type="text/javascript"></script>
@endsection

resources/views/shop/index.blade.php
@extends('layouts.panel')

@section('content-panel') 
    @include('shop.header')
    @if(in_array(Auth::user()->type,['administrator','seller']))
        <a href="{{ url('shops/create') }}"  class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>  {{ trans('process.create') }}</a><br/>
        <hr/>
    @endif
	@include('shop.datatable')
@endsection

resources/views/shop/list.blade.php
 <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
     <ul class="shops-list">
        @foreach ($shops as $shop)
        <a  href="{{ url('shops/'.$shop->id) }}">
            <li>
                <img src="http://placehold.it/120x120" />
                <div class="info">
                    <h2 class="title">{{ $shop->name }}</h2> 
                    <p class="desc">{{ $shop->business_name }}</p>
                    <label class="desc">{{ $shop->description }}</label>
                </div>
            </li>
        </a>
        @endforeach
    </ul>
</div>

resources/views/shop/show.blade.php
@extends('layouts.panel')

@section('shop-breadcrumbs')  
    @if($shop->id)
        <li><a href="{{ url('shops/'.$shop->id) }}">{{ trans('process.update') }}</a></li>
    @else
        <li><a href="{{ url('shops/create') }}">{{ trans('process.create') }}</a></li>
    @endif
@endsection

@section('content-panel') 
    @include('shop.header')

    @if($shop->id != '') 
        <ul class="nav nav-tabs">
            @if(in_array(\Auth::user()->type, ['administrator', 'operator']))
                <li class="active"><a href="#shop-form" data-toggle="tab">{{ trans('data.data') }}</a></li>
                <li><a href="#shopimage" data-toggle="tab">{{ trans('models.images') }}</a></li>
                <li><a href="#product-list" data-toggle="tab">{{ trans('models.products') }}</a></li>
                <li><a href="#shopbeacon-list" data-toggle="tab">{{ trans('models.beacons') }}</a></li>
            @endif

            @if(in_array(\Auth::user()->type, ['seller']))
                <li class="active"><a href="#shop-form" data-toggle="tab">{{ trans('data.data') }}</a></li>
                <li><a href="#shopimage" data-toggle="tab">{{ trans('models.images') }}</a></li>
            @endif
        </ul>
    @else
        <ul class="nav nav-tabs">
            <li class="active"><a href="#shop-form" data-toggle="tab">{{ trans('data.data') }}</a></li>
            @php /*<li><a href="#shopimage" data-toggle="tab">{{ trans('models.images') }}</a></li>*/@endphp
        </ul>
    @endif
 
    <div class="tab-content">
        <div class="tab-pane fade in active" id="shop-form">@include('shop.form')</div>

        @if(in_array(\Auth::user()->type, ['administrator', 'operator']))
            @if($shop->id != '')
                <div class="tab-pane fade" id="product-list">@include('product.list')</div>
                <div class="tab-pane fade" id="product-form">@include('product.form')</div>
            @endif
        @endif

        <div class="tab-pane fade" id="shopimage">
            <div class="col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
                <div role="alert" class="alert alert-primary alert-icon alert-icon-colored">
                    <div class="icon"><span class="mdi mdi-info-outline"></span></div>
                    <div class="message">
                        <strong>Seleccione las imágenes a mostrar de la portada de su negocio.</strong>
                        <ul>
                            <li>Formato: JPG o PNG</li>
                            <li>Tamaño mínimo: 800 x 400 px</li>
                            <li>Tamaño máximo: 1280 x 720 px</li>
                        </ul>
                    </div>
                </div>
            </div>
            @include('shopimage.form')
            <div id="shopimage-list" class="col-xs-12">@include('shopimage.list')</div>
        </div>

        @if(in_array(\Auth::user()->type, ['administrator', 'operator']))
            @if($shop->id != '')
                <div class="tab-pane fade" id="shopbeacon-list">@include('shopbeacon.list')</div>
                <div class="tab-pane fade" id="shopbeacon-form">@include('shopbeacon.form')</div>
            @endif
        @endif
    </div>
@endsection

@section('footer')
    @php /*<script src="{{ URL::asset('js/users/pattern-phone.js') }}" type="text/javascript"></script> */@endphp
    <script src="{{ URL::asset('js/imagesAjax.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/show.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/gmap.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/showLocalities.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/sortImages.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/shops/newForm.js') }}" type="text/javascript"></script>
    @if($shop->id)
        <script src="{{ URL::asset('js/products/offersCalculate.jquery.js') }}" type="text/javascript"></script>
    @endif
    <script src="{{ URL::asset('js/products/selectWords.jquery.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/products/addWord.jquery.js') }}" type="text/javascript"></script>
@endsection