routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::resource('shops', 'ShopController');
Route::post('shops/{id}/set-active', 'ShopController@setActiveStatus');
Route::post('shops/sort-images/', 'ShopController@sortImages');
Route::get('shops/{id}/products', 'ShopController@showProducts');

Route::resource('shop-images', 'ShopImageController');
Route::get('shop-images/shop/{id}', 'ShopImageController@showByShop');
Route::get('shops/{id}/set-image', 'ShopController@setImageAfterCreate');
Route::get('shops/check-images/{id}', 'ShopController@checkIfHaveImages');

Route::resource('words', 'WordController');

Route::resource('users', 'UserController');

Route::post('categories/sort-images/', 'CategoryController@sortImages');
Route::resource('categories', 'CategoryController');

Route::resource('category-images', 'CategoryImageController');
Route::get('category-images/category/{id}', 'CategoryImageController@showByCategory');

Route::resource('products', 'ProductController');
Route::post('products/sort-images', 'ProductController@sortImages');
Route::get('products/{id}/set-image', 'ProductController@setImageAfterCreate');
Route::get('products/check-images/{id}', 'ProductController@checkIfHaveImages');
Route::post('products/{id}/set-active', 'ProductController@setActiveStatus');

Route::resource('product-images', 'ProductImageController');
Route::get('product-images/product/{id}', 'ProductImageController@showByProduct');

Route::post('product-offers/calculate', 'ProductOfferController@calculate');

Route::resource('messages', 'MessageController');
Route::get('send-to-ios', 'MessageController@sendIOS');
Route::post('messages/send/{id}', 'MessageController@send');

Route::resource('beacons', 'ShopBeaconController');
Route::get('beacon/generate', 'ShopBeaconController@generateSerial');

Route::resource('products-beacon', 'ProductBeaconController');

Route::get('province/localities/{id}','ProvinceController@showLocalities');

Route::get('public_content', 'ContentController@public');
Route::get('content', 'ContentController@index');
Route::post('content', 'ContentController@store');


Route::get('help', 'HelpController@index');
Route::post('help', 'HelpController@store');

Route::resource('clients', 'ClientController');

Route::get('banners', 'BannerController@index');
Route::post('banners','BannerController@store');
Route::put('banners', 'BannerController@update');

Route::get('payments', 'PaymentController@index');
Route::get('payments/{id}', 'PaymentController@show');
Route::put('payments/{id}', 'PaymentController@update');

Route::post('mp/notifications', 'MPController@notifications');
//Route::post('mp/notifications', 'MPController@notifications');

Route::get('statistics', 'StatisticsController@index');
Route::get('statistics/{id}', 'StatisticsController@index');

app/Models/ProductImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Storage;
use File;
use App\Helpers\ImagesResize;


class ProductImage extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'product_images';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_id',
        'image',
        'order',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function products()
    {
        return $this->belongsTo('App\Models\Product');
    }
     /**
     * Update ShopImages in the database.
     *
     * @param  array  $attributes
     * @param  array  $options
     * @return bool
     */
    public function update(array $attributes = [], array $options = [])
    {
        $this->fill($attributes)->save();
        if($this->product_id)
            $this->image = 'storage/'. env('STORAGE_PRODUCT_IMAGES') . '/' . $attributes['product_id'].'_'.$this->id.'.jpg';

        if(array_key_exists ( 'file_image',  $attributes )){
            $file_image = File::get($attributes['file_image']);
            $image =     $attributes['product_id'].'_'.$this->id.'.jpg';
            $image_sm = $attributes['product_id'].'_'.$this->id.'_sm.jpg';

            Storage::put('/public/'. env('STORAGE_PRODUCT_IMAGES') . '/' . $image, $file_image);
            Storage::put('/public/'. env('STORAGE_PRODUCT_IMAGES') . '/' . $image_sm, $file_image);

            $path = public_path().'/..'.'/storage/app/'.'/public/'. env('STORAGE_PRODUCT_IMAGES') . '/';

            ImagesResize::maxSize($path,$image,1080,1920);
            ImagesResize::maxSize($path,$image_sm,480,480);
        }
        return $this->save();
    }

    public function delete()
    {       
        $image_sm = $this->product_id.'_'.$this->id.'_sm.jpg';
        $image = $this->product_id.'_'.$this->id.'.jpg';

        Storage::delete('/public/'. env('STORAGE_PRODUCT_IMAGES') . '/' . $image);
        Storage::delete('/public/'. env('STORAGE_PRODUCT_IMAGES') . '/' . $image_sm);

        if (is_null($this->getKeyName())) {
            throw new Exception('No primary key defined on model.');
        }
        if ($this->exists) {
            if ($this->fireModelEvent('deleting') === false) {
                return false;
            }
            $this->touchOwners();
            $this->performDeleteOnModel();
            $this->exists = false;
            $this->fireModelEvent('deleted', false);
            return true;
        }
    }     

    public function updateFileNames()
    {
        Storage::move('/public/'. env('STORAGE_PRODUCT_IMAGES') . '/_'.$this->id.'.jpg','/public/'. env('STORAGE_PRODUCT_IMAGES') . '/' . $this->product_id.'_'.$this->id.'.jpg');
        Storage::move('/public/'. env('STORAGE_PRODUCT_IMAGES') . '/_'.$this->id.'_sm.jpg','/public/'. env('STORAGE_PRODUCT_IMAGES') . '/' . $this->product_id.'_'.$this->id.'_sm.jpg');
    }

    /**
     * return name of small image
     * @return string 
     */
    public function getImageSmAttribute()
    {
        $image_sm = explode('.', $this->image);
        if(count($image_sm) > 1){
            return $image_sm[0] . '_sm.' . $image_sm[1];
        }
        return 'storage'. env('STORAGE_PRODUCT_IMAGES') . '/' . $this->product_id.'_'.$this->id.'_sm.jpg';
    }


    /**
     * return name of small image
     * @return string 
     */
    public function getImageLgAttribute()
    {
        $image_sm = explode('.', $this->image);
        if(count($image_sm) > 1){
            return $this->image;
        }
        return 'storage/' . env('STORAGE_PRODUCT_IMAGES') . '/' . $this->product_id.'_'.$this->id.'.jpg';
    }
}

app/Http/Controllers/ProductImageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductImage\StoreRequest; 
use App\Http\Requests\ProductImage\UpdateRequest; 
use Illuminate\Support\Facades\Request;
use Storage;
use File;
use Response;
// Models
use App\Models\Product;
use App\Models\ProductImage;

class ProductImageController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('user.type:administrator,seller');
    }

    /**
     * Display all images from shop
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showByProduct($id)
    {
        if(! is_numeric($id) ){
            $product = new Product();
            $product->images = ProductImage::where('product_id',null)->where('image',$id)->get();
        }else{
            $product = Product::find($id);
        }
        return view('productimage.list',compact('product'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        if($request->ajax())
        {
            $request['product_id'] = ($request['product_id']) ? $request['product_id'] : null;

            if (ProductImage::where('product_id', $request['product_id'])->count() >= intval(ENV('STORAGE_PRODUCT_MAX_IMAGES',1))) {
                //Si estas leyendo esto, gracias Juan!

                return Response::json([
                    'error' => 'Cantidad maxima de imagenes (' . intval(ENV('STORAGE_PRODUCT_MAX_IMAGES',1)) . ') superada.'
                ], 500);
            }

            $productimage = new ProductImage();
            $request['file_image'] = $request->images;
            $request['image'] = $request->_token;
            $productimage->update($request->all());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $path = storage_path() . '/app/' . env('STORAGE_PRODUCT_IMAGES') . '/' . $id;

        if(!File::exists($path)) abort(404);

        $file = File::get($path);
        $type = File::mimeType($path);

        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);

        return $response;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $productimage = ProductImage::find($id);
        $productimage->delete();
        flash( trans('process.success',['model' => trans('models.image.article') , 'process' => trans('process.deleted') ]) , 'success');
        return redirect()->back();    
    }
}

resources/views/productimage/form.blade.php
<div class="col-md-8 col-md-offset-2">
	{!! csrf_field() !!}
	<input type="hidden" name="product_id"  value="{{ $product->id }}" />
	<form  method="POST" action="{{ url('product-images') }}" id="productimages" class="dropzone" enctype="multipart/form-data">
	</form>
	<br/>
</div>

resources/views/productimage/list.blade.php
@if(count($product->images))
    <legend>{{ trans('data.list',['model' => trans('models.images') ]) }}</legend>

    <div class="images-grid">
        @foreach($product->images as $image)
            <div class="image">
                <a href="#" class="btn-left fa fa-chevron-left"></a>
                <a href="#" class="btn-right fa fa-chevron-right"></a>
                <input type="hidden" name="images[]" class="images-id" value="{{ $image->id }}">
                <input type="hidden" id="productId" value="{{ $product->id }}">
                <a href="{{ url($image->image_lg) }}" data-lightbox="shop-images" data-title="<a href='{{ url($image->image_lg) }}' class='mdi mdi-zoom-in'></a>">
                    <img src="{{ url($image->image_sm) }}"/>
                </a>
                <form action='{{ url('product-images/'.$image->id ) }}' method='POST' class="image-delete">
                    <input type="hidden" name="_method" value="DELETE">
                    {{ csrf_field()}}
                    <button class="btn btn-danger btn-delete">X</button>
                </form>
            </div>
        @endforeach
    </div>

    <button class="btn btn-primary" onclick="sortImages()">Actualizar Orden</button>
@endif

resources/views/productimage/list_set.blade.php
@if(count($product->images))
    <legend>{{ trans('data.list',['model' => trans('models.images') ]) }}</legend>

    <div class="images-grid">
        @foreach($product->images as $image)
            <div class="image">
                <a href="#" class="btn-left fa fa-chevron-left"></a>
                <a href="#" class="btn-right fa fa-chevron-right"></a>
                <input type="hidden" name="images[]" class="images-id" value="{{ $image->id }}">
                <input type="hidden" id="productId" value="{{ $product->id }}">
                <a href="{{ url($image->image_lg) }}" data-lightbox="shop-images" data-title="<a href='{{ url($image->image_lg) }}' class='mdi mdi-zoom-in'></a>">
                    <img src="{{ url($image->image_sm) }}"/>
                </a>
                <form action='{{ url('product-images/'.$image->id ) }}' method='POST' class="image-delete">
                    <input type="hidden" name="_method" value="DELETE">
                    {{ csrf_field()}}
                    <button class="btn btn-danger btn-delete">X</button>
                </form>
            </div>
        @endforeach
    </div>

    <button class="btn btn-primary" onclick="sortImages()">Actualizar Orden</button>
@endif