routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::resource('shops', 'ShopController');
Route::post('shops/{id}/set-active', 'ShopController@setActiveStatus');
Route::post('shops/sort-images/', 'ShopController@sortImages');
Route::get('shops/{id}/products', 'ShopController@showProducts');

Route::resource('shop-images', 'ShopImageController');
Route::get('shop-images/shop/{id}', 'ShopImageController@showByShop');
Route::get('shops/{id}/set-image', 'ShopController@setImageAfterCreate');
Route::get('shops/check-images/{id}', 'ShopController@checkIfHaveImages');

Route::resource('words', 'WordController');

Route::resource('users', 'UserController');

Route::post('categories/sort-images/', 'CategoryController@sortImages');
Route::resource('categories', 'CategoryController');

Route::resource('category-images', 'CategoryImageController');
Route::get('category-images/category/{id}', 'CategoryImageController@showByCategory');

Route::resource('products', 'ProductController');
Route::post('products/sort-images', 'ProductController@sortImages');
Route::get('products/{id}/set-image', 'ProductController@setImageAfterCreate');
Route::get('products/check-images/{id}', 'ProductController@checkIfHaveImages');
Route::post('products/{id}/set-active', 'ProductController@setActiveStatus');

Route::resource('product-images', 'ProductImageController');
Route::get('product-images/product/{id}', 'ProductImageController@showByProduct');

Route::post('product-offers/calculate', 'ProductOfferController@calculate');

Route::resource('messages', 'MessageController');
Route::get('send-to-ios', 'MessageController@sendIOS');
Route::post('messages/send/{id}', 'MessageController@send');

Route::resource('beacons', 'ShopBeaconController');
Route::get('beacon/generate', 'ShopBeaconController@generateSerial');

Route::resource('products-beacon', 'ProductBeaconController');

Route::get('province/localities/{id}','ProvinceController@showLocalities');

Route::get('public_content', 'ContentController@public');
Route::get('content', 'ContentController@index');
Route::post('content', 'ContentController@store');


Route::get('help', 'HelpController@index');
Route::post('help', 'HelpController@store');

Route::resource('clients', 'ClientController');

Route::get('banners', 'BannerController@index');
Route::post('banners','BannerController@store');
Route::put('banners', 'BannerController@update');

Route::get('payments', 'PaymentController@index');
Route::get('payments/{id}', 'PaymentController@show');
Route::put('payments/{id}', 'PaymentController@update');

Route::post('mp/notifications', 'MPController@notifications');
//Route::post('mp/notifications', 'MPController@notifications');

Route::get('statistics', 'StatisticsController@index');
Route::get('statistics/{id}', 'StatisticsController@index');

app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use DB;
class Payment extends Model {

    protected $fillable = [
        'id',
        'user_id',    
        'shop_id',
        'product_id',
        'mp_payment_id',
        'status',
        'response',
        'delivery',
        'quantity',
        'payment_method',
        'payment_created_date',
        'delivery_date'
    ];
    
    public static function createPaymentV2($user_id, $data){        
        
        date_default_timezone_set("America/Argentina/Buenos_Aires");
        
        return self::create(array(
            "user_id" => $user_id,
            "shop_id" => $data["product"]["shop"]["id"],
            "product_id" => $data["product"]["prod_id"],
            "mp_payment_id" => $data["payment"]["id"],
            "status" => $data["payment"]["status"],
            "response" => json_encode($data),
            "quantity" => $data["quantity"],
            "payment_method" => $data["payment_method"],
            'payment_created_date' => date("Y-m-d H:i:s")
        ));

    }
  
    public static function createPayment($user_id, $data){        
        
        date_default_timezone_set("America/Argentina/Buenos_Aires");
        
        return self::create(array(
            "user_id" => $user_id,
            "shop_id" => $data["product"]["shop"]["id"],
            "product_id" => $data["product"]["id"],
            "mp_payment_id" => $data["payment"]["id"],
            "status" => $data["payment"]["status"],
            "response" => json_encode($data),
            "quantity" => $data["quantity"],
            "payment_method" => $data["payment_method"],
            'payment_created_date' => date("Y-m-d H:i:s")
        ));

    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function shop()
    {
        return $this->belongsTo('App\Models\Shop');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function product()
    {
        return $this->belongsTo('App\Models\Product');
    }
    
    /**
     * Get Date Formated
     *
     * @return date
     */
    public function getFullCreatedAttribute()
    {
        return  Carbon::parse($this->created_at)->format('d/m/Y h:i:s A');
    } 

    /**
     * Get Date Without hour
     *
     * @return date
     */
    public function getDateCreatedAttribute()
    {
        return  Carbon::parse($this->created_at)->format('d/m/Y');
    }
    /**
     * Get Only Hour
     *
     * @return date
     */
    public function getHourCreatedAttribute()
    {
        return  Carbon::parse($this->created_at)->format('h:i:s A');
    }

    public function getPedidoAttribute()
    {
        if($this->status != 'approved'){
            return "-";
        }
        $pedido = DB::table('payments')
                        ->where('id','<=',$this->id)
                        ->where('shop_id',$this->shop_id)
                        ->where('status','approved')->count();
        return $pedido;
    }

    public function getTransactionAmountAttribute()
    {
        $transactionAmount = isset($this->response->payment->transactionAmount) ? 
                             $this->response->payment->transactionAmount : 
                             $this->response->payment->transaction_amount;
        
        $price = number_format($transactionAmount ,2,",",".");
        return $price;
    }

    public function getStatusFormattedAttribute()
    {
        $status = '';
        switch ($this->status) {
            case 'pending':
                    $status = 'Pendiente';
                break;
            case 'approved':
                    $status = 'Recibido';
                break;
            case 'in_process':
                    $status = 'En Progreso';
                break;
            case 'in_mediation':
                    $status = 'En Mediación';
                break;
            case 'rejected':
                    $status = 'Rechazado';
                break;
            case 'cancelled':
                    $status = 'Cancelado';
                break;
            case 'refunded':
                    $status = 'Reintegrado';
                break;
            case 'charged_back':
                    $status = 'Devuelto';
                break; 
        }

        return $status;
    }
  
}

app/Models/PaymentType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PaymentType extends Model {

  protected $fillable = [
    'name',
    'key'
  ];

  public static function getByKey($key)
  {
    return self::where(['key' => $key])->get()->first();
  }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Notifications\ResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Hash;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\UserSetting;
// 
use App\Models\Product;
use App\Models\Shop;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'type',
        'email',
        'password',
        'register_id',
        'first_name',
        'last_name',
        'birthday',
        'phone',
        'gender',
        'from',
        'image',
        'active',
        'config',
        'provider_id',
        'provider_access_token',
        'created_by',
        'device_os'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function shops()
    {
        return $this->belongsToMany('App\Models\Shop', 'pivot_user_shops', 'user_id','shop_id');
    }

    public function favorites()
    {
        return $this->hasMany('App\Models\UserFavorite');
    }

    public function settings()
    {
        return $this->hasOne('App\Models\UserSetting');
    }
    
    public function interests()
    {
        return $this->hasOne('App\Models\UserInterests');
    }
    
    public function getSettings()
    {
        $settings = $this->settings()->first();

        if ($settings) {
            return $settings;
        }
        
        $settings = $this->settings()->create([]);

        return $settings;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function products()
    {
        $user = auth()->user();

        switch($this->type)
        {
            case 'administrator':
                return Product::orderBy('name','asc')->get();

            case 'operater':
                $shops = $this->shops()->get();
                $products = [];
                foreach ($shops as $shop) {
                    $products = $shop->products()->get()->merge($products);
                }
                if( $products ){
                    return $products->sortBy('name');
                }
                return $products;

            case 'seller':

                return Product::whereHas('shop', function($subQuery){
                    $subQuery->whereHas('creator',function($subSubQuery){
                        $subSubQuery->where('id', auth()->user()->id);
                    });
                })->orderBy('name','asc')->get();
        }

        $shops = $this->shops()->get();
        $products = [];
        foreach ($shops as $shop) {
            $products = $shop->products()->get()->merge($products);
        }
        if( $products ){
            return $products->sortBy('name');
        }
        return $products;

        /* TOdo: Hacer bien, borrar los foreachs furiosos
         * $user = $this;

        return Product::whereHas('shop.users', function ($subQuery) use ($user){
            $subQuery->where('user.id', $user->id);
        })->orderBy('name','asc')
          ->get();


        );
         */
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function payments()
    {
        $products = $this->products();
        $payments = [];
        foreach ($products as $product) {
            $payments = $product->payments()->get()->merge($payments);
        }
        return $payments;
    }

    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder $query
     * //Scope para traer facilmente los usuarios que pueden ser asignados a un shop como operadores
     * Si es admin, trae todos los operadores, si es vendedor, los operadores que haya creado el
     */
    public function scopeAsignable($query)
    {
        return $query->accesible()->where('type','operator');
    }

    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder $query
     * //Scope para traer facilmente los usuarios que se pueden ver
     */
    public function scopeAccesible($query)
    {
        $user = Auth::user();

        switch($user->type)
        {
            case 'administrator': //El admin ve everything
                return $query;

            case 'seller': //El vendedor solo ve los usuarios que creo el mismo

                return $query->whereHas('creator', function ($subQuery) use ($user){
                        $subQuery->where('id', $user->id);
                    }
                );

            case 'operator': //El operador no puede ver usuarios

                return $query->where('id', null); //Todo: Vacio siempre, ver una manera decente
        }

        throw new \Exception('El usuario no puede ver usuarios');
    }

    /**
    * Get Date Formated
    *
    * @return date
    */
    public function getFullCreatedAttribute()
    {
        return  Carbon::parse($this->created_at)->format('d/m/Y h:i:s A');
    }

    /**
    * Get Date Formated
    *
    * @return date
    */
    public function getCreatedAttribute()
    {
        return  Carbon::parse($this->created_at)->format('d/m/Y');
    }

    public function creator()
    {
        return $this->belongsTo('App\Models\User','created_by');
    }

    public function usersCreated()
    {
        return $this->hasMany('App\Models\User','created_by');
    }

    public function shopsCreated()
    {
        return $this->hasMany('App\Models\Shop','created_by');
    }

    /**
    * Get User Full Name
    *
    * @return string
    */
    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public static function createUser(array $data)
    {
        $data['type'] = 'user';
        $data['active'] = 1;
        if( !array_key_exists ( 'gender',  $data ) ){
            $data['gender'] = 'Otro';
        }
        return self::create($data);
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
// Models
use App\Models\Payment;
use App\Models\Product;
use App\Models\Shop;
use App\Models\UserPoint;

class PaymentController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }   

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $payments =  Auth::user()->payments();
      $shops = Shop::orderBy('name','desc')->get();  
      return view('payment.index',compact('payments','shops'));
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $payment = Payment::with(['user', 'product'])->find($id); 
        $payment->response = json_decode($payment->response);
//        die(var_dump($payment->toArray()));
        $title = trans('process.update');
        $post = url('payments/'.$payment->id);
        
        return view('payment.form',compact('payment','title','post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $payment = Payment::find($id);          
        $payment->status = $request->status;
        $payment->delivery = $request->delivery;
        $payment->payment_method = $request->payment_method;
        $payment->payment_comment = $request->payment_comment;
        $payment->payment_observations = $request->payment_observation;
                
        $response = json_decode($payment->response);
        $response->payment->status = $request->status;
        
        $payment_created_date = explode("/", $request->payment_created_date);
        $delivery_date = explode("/", $request->delivery_date);
        
//        die(date($payment_created_date[2]."/".$payment_created_date[1]."/".$payment_created_date[0]));
        $payment->payment_created_date = date($payment_created_date[2]."/".$payment_created_date[1]."/".$payment_created_date[0]);
        $payment->delivery_date = date($delivery_date[2]."/".$delivery_date[1]."/".$delivery_date[0]);
        $payment->response = json_encode($response);
        $payment->save();
        
        if( $request->status == "approved"){
            
            $product = Product::find($payment->product_id);
            
            if( $product->point > 0){
                
                UserPoint::saveUserPoints([
                    'user_id' => $payment->user_id,
                    'shop_id' => $payment->shop_id,
                    'point' => $product->point,
                ]);
                
            }
            
        }
        
        return redirect('payments');
    }
}

resources/views/payment/filter.blade.php
<div class="form-group text-center user-wrapper">
    <div class="col-sm-2 user-filter hidden-xs">
        <label>Mostrar</label>
        <select id="filter-length" class="form-control input-sm" >
            <option value="10">10</option>
            <option value="25">25</option>
            <option value="50">50</option>
            <option value="100" selected>100</option>
        </select>
    </div>



    <div class="col-sm-2 user-filter">
        <label class="filter-pay-label">{{ trans('data.pay.status') }}</label>
        <select id="filter-pay-status" class="form-control input-sm">
            <option>Todos</option>
            <option>Pendiente</option>
            <option>Recibido</option>
            <option>Devuelto</option>
        </select>
    </div>

    <div class="col-sm-2 user-filter">
        <label>{{ trans('data.created') }}</label>
        <input type="text" id="date-created" class="form-control input-sm text-center">
    </div>    

    <div class="col-sm-2 user-filter">
        <label>{{ trans('data.delivery') }}</label>
        <select id="filter-delivery" class="form-control input-sm">
                <option>Todos</option>
                <option>Concretada</option>
                <option>Pendiente</option>
                <option>Cancelada</option>
        </select>
    </div>
    @if( Auth::user()->type == 'administrator')
    <div class="col-sm-2 user-filter">
        <label>{{ trans('models.shop') }}</label>
        <select id="filter-shop" class="form-control input-sm select2">
                    <option>Todos</option>
                @foreach($shops as $shop)
                    <option>{{ $shop->name }}</option>
                @endforeach
        </select>
    </div>
    @endif
    <div class="col-sm-2 user-filter">
        <label>Buscar</label>
        <input type="text" id="filter-search" class="form-control input-sm text-center">
    </div>
</div> 

resources/views/payment/form.blade.php
@extends('layouts.panel')

@section('payment-breadcrumbs')  
<li><a href="{{ url('payments/'.$payment->id) }}">{{ trans('process.update') }}</a></li>
@endsection

@section('content-panel')
@include('payment.header')
<br/>  
<form role="form" method="POST" action="{{ url('payments/'.$payment->id) }}" class="form-horizontal group-border-dashed"> 
    <input type='hidden' name='_method' value='PUT'>
    {{ csrf_field() }}

    <div class="clearfix"></div>
        <h3 class="page-head-title" style="font-size: 1.7em;">Pago</h3>
    <div class="clearfix"></div>
    <div class="col-lg-8">
        <div class="col-lg-6">
            <p><span style="font-size: 1.1em;font-weight: bolder;color: #333">Producto:</span> <span>{{ $payment->product->name }}</span></p>
        </div>
        <div class="col-lg-6">
            <p><span style="font-size: 1.1em;font-weight: bolder;color: #333">Precio: </span><span>$ {{ $payment->transaction_amount }}</span></p>
        </div>
    </div>
<div class="clearfix"></div>
    <div class="col-lg-8">
        <div class="col-lg-6">
            <p><span style="font-size: 1.1em;font-weight: bolder;color: #333">Comprador: </span><span><?= empty($payment->user->first_name) || empty($payment->user->last_name) ? $payment->user->email : $payment->user->first_name . " " . $payment->user->last_name; ?></span></p>
        </div>
        <div class="col-lg-6">
            <p><span style="font-size: 1.1em;font-weight: bolder;color: #333">Puntos:</span> <span>{{ $payment->response->product->point }}</span></p>
        </div>
    </div>
<div class="clearfix"></div>
    <div class="col-lg-8">
        <div class="col-lg-6">
        </div>
        <div class="col-lg-6">
            <p><span style="font-size: 1.1em;font-weight: bolder;color: #333">Cantidad: </span><span>{{ $payment->response->quantity }}</span></p>
        </div>
    </div>
<div class="clearfix"></div>
<div class="col-lg-8">
    
    <div class="form-group col-lg-5" style="display: flex;">
        <label style="padding: 0;line-height: 35px;margin-left: 5px"  class="col-lg-5 control-label">{{ trans('data.pay.status') }}</label>
        <div class="col-lg-7">
            <select name="status" class="form-control input-sm" required>
                    <option value="pending"      @if($payment->status == 'pending') selected @endif >Pendiente</option>
                    <option value="approved"     @if($payment->status == 'approved') selected @endif >Aprobado</option>
                   {{--  <option value="in_process"   @if($payment->status == 'in_process') selected @endif >En Progreso</option> --}}
                   {{--  <option value="in_mediation" @if($payment->status == 'in_mediation') selected @endif >En Mediación</option> --}}
                   {{--  <option value="rejected"     @if($payment->status == 'rejected') selected @endif >Rechazado</option> --}}
                   {{--  <option value="cancelled"    @if($payment->status == 'cancelled') selected @endif >Cancelado</option> --}}
                   {{--  <option value="refunded"     @if($payment->status == 'refunded') selected @endif >Reintegrado</option> --}}
                    <option value="charged_back" @if($payment->status == 'charged_back') selected @endif >Devuelto</option>
            </select>
        </div>
    </div>
    
    <div class="form-group col-lg-5 col-lg-push-1" style="display: flex;">
        <label style="padding: 0;line-height: 35px;margin-left: 5px" class="col-lg-4 control-label">El día</label>
        <div class="col-lg-8">
            <div style="padding-top: 0;" data-min-view="2" data-date-format="dd/mm/yyyy" class="input-group date datetimepicker">
                <input value="<?= date("d/m/Y", strtotime($payment->payment_created_date)) ?>" autocomplete="off" style="padding: 0;height: 32px" type="text" size="16" name="payment_created_date" class="form-control input-sm" />
                <span class="input-group-addon btn btn-primary"><i class="icon mdi mdi-calendar"></i></span>
            </div>
        </div>
    </div>
    
</div>

<div class="col-lg-8">
    <div class="form-group col-lg-5" style="display: flex;">
        <label style="padding: 0;line-height: 35px;margin-left: 5px"  class="col-lg-5 control-label">Método de pago</label>
        <div class="col-lg-7">
            <select autocomplete="off" name="payment_method" class="form-control input-sm" required>
                <option value="mp" class="mp" <?= $payment->payment_method == 'mp' ? "selected=true": "" ?>>Mercado Pago</option>
                <option value="cash" class="cash" <?= $payment->payment_method == 'cash' ? "selected=true": "" ?>>Efectivo</option>
            </select>
        </div>
    </div>
    
    <div id="payment_comment" class="form-group col-lg-5 col-lg-push-1" style="<?= $payment->payment_method == 'mp' ? "display:none" : "" ?>">
        <div class="col-xs-10 col-lg-push-2">
            <textarea placeholder="Detalle" name="payment_comment" style="max-width: 100%;min-width: 100%;max-height: 75px;min-height: 75px"><?= $payment->payment_comment ?></textarea>
        </div>
    </div>
    
</div>
<div class="clearfix"></div>
<h3 class="page-head-title" style="font-size: 1.7em;">Entrega</h3>
<div class="clearfix"></div>
<div class="col-lg-8">
    
    <div class="form-group col-lg-5">
        <label  class="col-lg-5 control-label">{{ trans('data.delivery') }}</label>
        <div class="col-sm-7 ">
            <select name="delivery" class="form-control input-sm" required>
                    <option value="Concretada"      @if($payment->delivery == 'Concretada') selected @endif >Concretada</option>
                    <option value="Pendiente"     @if($payment->delivery == 'Pendiente') selected @endif >Pendiente</option>
                    <option value="Cancelada"   @if($payment->delivery == 'Cancelada') selected @endif >Cancelada</option>
            </select>
        </div>
    </div> 
    
    <div class="form-group col-lg-5 col-lg-push-1" style="display: flex;">
        <label style="padding: 0;line-height: 35px;margin-left: 5px" class="col-lg-4 control-label">Fecha</label>
        <div class="col-lg-8">
            <div style="padding-top: 0;" data-min-view="2" data-date-format="dd/mm/yyyy" class="input-group date datetimepicker">
                <input style="padding: 0;height: 32px" value="<?= $payment->delivery_date == "0000-00-00" || !$payment->delivery_date ? date("d/m/Y") : date("d/m/Y", strtotime($payment->delivery_date)); ?>" type="text" size="16" name="delivery_date" class="form-control input-sm" />
                <span class="input-group-addon btn btn-primary"><i class="icon mdi mdi-calendar"></i></span>
            </div>
        </div>
    </div>
</div>    
    
    <div class="form-group col-lg-12">
        <div class="col-xs-7">
        <label style="padding: 0;line-height: 35px;margin-left: 5px"  class="control-label">Observaciones</label>
            <textarea name="payment_observation" style="max-width: 100%;min-width: 100%;max-height: 100px;min-height: 100px"><?= $payment->payment_observations ?></textarea>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary"> @if($payment->id)<span class="icon mdi mdi-edit"></span>  {{ trans('process.save') }} @else <span class="glyphicon glyphicon-plus"></span>  {{ trans('process.create') }}  @endif</button>
            <a href="{{ url('/payments') }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>   {{ trans('process.back') }}</a> 
        </div>
    </div>
</form>
@endsection

@section('footer')
    
    <script type="text/javascript">
               
        $(document).ready(function(){

            $("body").on("change", "select[name='payment_method']", function(){

                if($(this).val() === "cash"){
                    $("#payment_comment").show();
                }else{
                    $("#payment_comment").hide();
                }

            });

        });
        
    </script>

@endsection

resources/views/payment/header.blade.php
@section('containt-title') {{ trans('models.payments') }} @endsection

@section('menu-ventas') class="active" @endsection

@section('breadcrumbs') 
    <li><a href="{{ url('payments') }}" >{{ trans('models.list',['model'=>trans('models.payments')] ) }}</a></li>
    @yield('payment-breadcrumbs')
@endsection

resources/views/payment/index.blade.php
@extends('layouts.panel')

@section('head')
<link rel="stylesheet" type="text/css" href="{{ URL::asset('lib/bootstrap-daterangepicker/daterangepicker.css') }}"/>
@endsection

@section('content-panel')
@include('payment.header')
 <br/>
@include('payment.filter')
<table class="table table-striped table-condensed" id="payment-datatable">
    <thead>
        <tr>
            <th class="col col-xs-1 text-center">{{ trans('data.id') }}</th> 
            <th class="col col-xs-1">{{ trans('models.product') }}</th> 
            <th class="col col-xs-1"> Importe </th> 
            <th class="col col-xs-2">{{ trans('models.user.generic') }}</th>  
            <th class="col col-xs-1">{{ trans('data.phone') }}</th> 
            <th class="col col-xs-1">{{ trans('data.email') }}</th> 
            <th class="col col-xs-2">{{ trans('data.date.full') }}</th>  
            <th class="col col-xs-2">{{ trans('data.pay.status') }}</th>  
            <th class="col col-xs-1">{{ trans('data.delivery') }}</th>  
            <th class="col col-xs-1">Pedido</th>  
            @if(Auth::user()->type == 'administrator')
                <th class="col col-xs-1">{{ trans('models.shop') }}</th>  
            @endif
            <th class="col col-xs-1">{{ trans('data.action') }}</th>
        </tr>
    </thead>
    <tbody>
        @if(!$payments->isEmpty())
            @foreach($payments as $payment)
                <tr >
                    <td class="text-center">{{ $payment->id }}</td>
                    <td class="text-center">{{ $payment->product->name }}</td>
                    <td class="text-center">{{ $payment->product->price }}</td>
                    @if($payment->user)
                        <td class="text-center">{{ $payment->user->full_name }}</td>
                        <td class="text-center">{{ $payment->user->phone }}</td>
                        <td class="text-center">{{ $payment->user->email }}</td>
                    @else
                        <td class="text-center">-</td>
                        <td class="text-center">-</td>
                        <td class="text-center">-</td>
                    @endif
                    <td class="text-center">{{ $payment->full_created }}</td>
                    <td class="text-center">{{ $payment->status_formatted }}</td>
                    <td class="text-center">{{ $payment->delivery }}</td>
                    <td class="text-center">{{ $payment->pedido }}</td>
            @if(Auth::user()->type == 'administrator' && isset($payment->shop))
                    <td class="text-center">{{ $payment->shop->name }}</td>
            @else
                <td class="text-center">-</td>
            @endif
                <td class="text-center">
                    <a class="icon mdi mdi-edit btn btn-primary" href="{{ url('payments/'.$payment->id) }}" data-toggle="tooltip" title="{{ trans("process.update") }}"></a>
                </td>
            </tr>
            @endforeach
        @else
            <tr>
                <td class="text-center" colspan="12">No hay data</td>
            </tr>
        @endif
    </tbody>
</table>
@endsection

@section('footer')
    <script src="{{ URL::asset('js/payments/paymentsDatatableFilter.jquery.js') }}" type="text/javascript"></script>

@endsection