routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::resource('shops', 'ShopController');
Route::post('shops/{id}/set-active', 'ShopController@setActiveStatus');
Route::post('shops/sort-images/', 'ShopController@sortImages');
Route::get('shops/{id}/products', 'ShopController@showProducts');

Route::resource('shop-images', 'ShopImageController');
Route::get('shop-images/shop/{id}', 'ShopImageController@showByShop');
Route::get('shops/{id}/set-image', 'ShopController@setImageAfterCreate');
Route::get('shops/check-images/{id}', 'ShopController@checkIfHaveImages');

Route::resource('words', 'WordController');

Route::resource('users', 'UserController');

Route::post('categories/sort-images/', 'CategoryController@sortImages');
Route::resource('categories', 'CategoryController');

Route::resource('category-images', 'CategoryImageController');
Route::get('category-images/category/{id}', 'CategoryImageController@showByCategory');

Route::resource('products', 'ProductController');
Route::post('products/sort-images', 'ProductController@sortImages');
Route::get('products/{id}/set-image', 'ProductController@setImageAfterCreate');
Route::get('products/check-images/{id}', 'ProductController@checkIfHaveImages');
Route::post('products/{id}/set-active', 'ProductController@setActiveStatus');

Route::resource('product-images', 'ProductImageController');
Route::get('product-images/product/{id}', 'ProductImageController@showByProduct');

Route::post('product-offers/calculate', 'ProductOfferController@calculate');

Route::resource('messages', 'MessageController');
Route::get('send-to-ios', 'MessageController@sendIOS');
Route::post('messages/send/{id}', 'MessageController@send');

Route::resource('beacons', 'ShopBeaconController');
Route::get('beacon/generate', 'ShopBeaconController@generateSerial');

Route::resource('products-beacon', 'ProductBeaconController');

Route::get('province/localities/{id}','ProvinceController@showLocalities');

Route::get('public_content', 'ContentController@public');
Route::get('content', 'ContentController@index');
Route::post('content', 'ContentController@store');


Route::get('help', 'HelpController@index');
Route::post('help', 'HelpController@store');

Route::resource('clients', 'ClientController');

Route::get('banners', 'BannerController@index');
Route::post('banners','BannerController@store');
Route::put('banners', 'BannerController@update');

Route::get('payments', 'PaymentController@index');
Route::get('payments/{id}', 'PaymentController@show');
Route::put('payments/{id}', 'PaymentController@update');

Route::post('mp/notifications', 'MPController@notifications');
//Route::post('mp/notifications', 'MPController@notifications');

Route::get('statistics', 'StatisticsController@index');
Route::get('statistics/{id}', 'StatisticsController@index');

app/Models/ShopBeacon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Formatters\Api\BeaconFormatter;

class ShopBeacon extends Model
{
    use BeaconFormatter;
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'shop_beacons';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'shop_id',
        'product_id',
        'serial',
        'distance',
        'description',
        'active',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function shop(){
        return $this->belongsTo('App\Models\Shop');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function product(){
        return $this->belongsTo('App\Models\Product');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function products_around(){
        return $this->hasOne('App\Models\ProductsBeacon','beacon_id');
    }

     /**
     * Update ShopImages in the database.
     *
     * @param  array  $attributes
     * @param  array  $options
     * @return bool
     */
    public function updateModified(array $attributes = [], array $options = [])
    {
        if(isset($attributes["serial"])){
            
            $serial = explode("/", $attributes["serial"]);
            
            $attributes["serial"] = hexdec($serial[0]) . "/" . hexdec($serial[1]);
            
        }
        
        $attributes['active'] = (array_key_exists ( 'active',  $attributes ))? true : false;
        return $this->fill($attributes)->save();
    }

    /**
     * Sólo beacons activos.
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeActive($query) {
        return $query->where('active', 1);
    }

    public static function makeSerial($major, $minor)
    {
      return "$major/$minor";
    }

    public static function suggestDistance($distance = 0)
    {
        if($distance <= 5){
            return 'close';
        }else{
            return 'far';
        }
    }

    public function scopeAccesible($query)
    {
        //ini_set('xdebug.max_nesting_level', 200);
        //Hola, si te tira error de nesting max, setea esto en php.ini o descomenta esta linea,
        // el framework nestea muchas funciones cuando usas las querys compuestas y si tenes xdebug desactualizado te puede dar error

        $user = \Auth::user();

        switch($user->type)
        {
            case 'administrator': //El admin ve everything
                return $query;

            case 'operator': //El operador ve los beacons de los shops de los que es operador asignado

                return $query->whereHas('shop', function ($subQuery) use ($user){ //shop.users ?
                        $subQuery->whereHas('users', function($subSubQuery) use ($user){
                            $subSubQuery->where('users.id', $user->id);
                        });
                    }
                );

            case 'seller': //El vendedor solo ve los beacons sin asignar a ningun shop o asignados a shops a los que tiene acceso

                return $query->doesntHave('shop')->orWhereHas('shop', function ($subQuery){
                        $subQuery->accesible();
                    }
                );
        }

        throw new \Exception('El usuario no tiene acceso a shops');
    }

    public function getSerialStringAttribute()
    {
        $serial = explode("/", $this->serial,2);
        $minor = str_pad( dechex(@$serial[0]), 4, "0", STR_PAD_LEFT);
        $mayor = str_pad( dechex(@$serial[1]), 4, "0", STR_PAD_LEFT);
        return  $minor . "/" . $mayor;
    }
    
    
    
}

app/Http/Controllers/ShopBeaconController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ShopBeacon\StoreRequest;
use App\Models\MessageStatistic;
use Illuminate\Support\Facades\Auth;
// Models
use App\Models\ShopBeacon;
use App\Models\Shop;
use App\Models\Product;

class ShopBeaconController extends Controller
{    
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shopBeacons = ShopBeacon::with([
            'shop',
            'product.offer',
            'products_around.product_close',
            'products_around.product_far'
        ])->accesible()->get();

        return view('shopbeacon.index', compact('shopBeacons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        if(!$this->getPermission(0))      
            return redirect('/beacons');

        $shops = Shop::accesible()->where('active', 1)->orderBy('name','asc')->get();
        $shopBeacon = new ShopBeacon();
        //$shopBeacon->serial = $this->get_next_serial();
        $title = trans('process.create');
        $post = url('beacons');
        return view('shopbeacon.show',compact('shopBeacon','shops','products','title','post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $shopBeacon = new ShopBeacon();
        $input = $request->input();
        $input['shop_id'] = $request->get('shop_id', null) > 0 ? $request->get('shop_id', null) : null;
        $shopBeacon->updateModified($input);
//        $shopBeacon->active = false;
        $shopBeacon->save();

        flash( trans('process.success',['model' => trans('models.beacon.article') , 'process' => trans('process.created') ]), 'success');
        return redirect('beacons');   
    }

    /**
     * Display the specified resource.z
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {        
        if(!$this->getPermission($id))
            return redirect('/beacons');

        $shopBeacon = ShopBeacon::find($id);

        $shops = Shop::accesible()->where('active', 1)->orderBy('name','asc')->get();

        if(Auth::user()->type == 'operator'){
            //$shops = Auth::user()->shops()->orderBy('name','asc')->get();
            $products = Auth::user()->products();
        }
        else
        {
            //$shops = Shop::orderBy('name','asc')->get();
            $products = Product::orderBy('name','asc')->get();
        }
        $title = trans('process.update');
        $post = url('beacons/'.$shopBeacon->id);
        
        return view('shopbeacon.show',compact('shopBeacon','title','post','shops','products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreRequest $request, $id)
    {
        if($this->getPermission($id))
        {
            $new_shop_id = $request->get('shop_id', 0) == 0 ? null : $request->get('shop_id');

            $shopBeacon = ShopBeacon::accesible()->findOrFail($id);

            /* inicio Quitamos las ofertas del beacon */
            if (count($shopBeacon->products_around) && ($new_shop_id != $shopBeacon->shop_id))
            { //Hay que ver como hacemos con el tema estadisticas, pero por ahora es mejor que no queden datos incoherentes si cambias el shop
                $shopBeacon->products_around->update([
                    'product_close_id' => null,
                    'product_far_id' => null,
                    'product_close_message' => '',
                    'product_far_message' => '',
                ]);

//                $shopBeacon->active = false;
            }
            /* fin Quitamos las ofertas del beacon */

            /* Reseteamos las estadisticas del beacon por cambio de shop */
            $statics = new MessageStatistic;
            $existing = $statics->where('products_beacon_id', $shopBeacon->id)->get();
            if($new_shop_id != $shopBeacon->shop_id && count($existing)){
                $statics->where('products_beacon_id', $shopBeacon->id)->update(['views' => 0, 'issues' => 0]);
            }

            $shopBeacon->fill($request->except(['shop_id']));
            
            if($request->get('serial')){
            
                $serial = explode("/", $request->get('serial'));
                
                $shopBeacon->serial = hexdec($serial[0]) . "/" . hexdec($serial[1]);

            }
            
            $shopBeacon->active = (array_key_exists ( 'active',  $request->all() )) ? true : false;
            
            $shopBeacon->shop_id = $new_shop_id;
            $shopBeacon->save();

            flash(trans('process.success', ['model' => trans('models.beacon.article'), 'process' => trans('process.updated')]), 'success');
            return redirect('beacons');
        }

        return redirect('beacons');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if($this->getPermission(0)){
            ShopBeacon::find($id)->destroy($id);
            flash( trans('process.success',['model' => trans('models.beacon.article') , 'process' => trans('process.deleted') ]), 'success');
        }
        return redirect('beacons');        
    }


    private function selectByUser()
    {
        $shops = Auth::user()->shops()->get();
        $beacons = [];
        foreach ($shops as $shop) {
            $beacons = $shop->beacons()->get()->merge($beacons);
        }
        return $beacons;
    }

    private function getPermission($id)
    {
        $user = \Auth::user();

        if($id == 0)
        {
            if(in_array($user->type,['administrator','seller'])){
                return true;
            }
        }

        if (ShopBeacon::accesible()->where('id', $id)->firstOrFail())
        {
            return true;
        }

        flash()->overlay( trans('process.alert.denied') , trans('process.denied') );
        return false;
    }

    public function generateSerial()
    {
        do {
            $serial = $this->beaconSerial();
            $count =  count(ShopBeacon::where('serial',$serial)->get());
        } while ($count > 0);
        return $serial;
    }

    private function beaconSerial()
    {   
        // Los cuatro digitos de la izquierda deben ser mayor 
        // a los cuatro digitos de la derecha.
        $x = 3;
        $min = pow(10,$x);
        $max = pow(10,$x+1)-1;
        $mayor = rand($min, $max);
        $minor = rand($min, $mayor);
        $serial = $mayor.'/'.$minor;
        return $serial;
    }

    private function get_next_serial(){
        $serial = $this->get_last_serial();
        $serial = explode('/', $serial);
        if( count($serial) > 1 ){
            $serial[0] = $serial[0] + 1;
            $serial[1] = $serial[1] + 1;
            $serial[0] = str_pad($serial[0], 4, '0', STR_PAD_LEFT);
            $serial[1] = str_pad($serial[1], 4, '0', STR_PAD_LEFT);
            return $serial[0] . '/' . $serial[1];
        }
    }
    private function get_last_serial(){                
        return \DB::table('shop_beacons')->select(['id','serial'])->orderBy('id', 'DESC')->first()->serial;
    }

}

resources/views/shopbeacon/form.blade.php
@if(isset($shop))
    <a href="#shopbeacon-list" data-toggle="tab" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-th-list"></span>   {{ trans('models.list',['model'=> trans('models.beacons')]) }}</a>
    <hr/>
    <form action="{{ url('beacons') }}" data-form="disable-on-submit" method="POST" role="form" id="save_changes" class="form-horizontal group-border-dashed">
@else
    <form action="{{ $post }}" data-form="disable-on-submit" method="POST" role="form" id="save_changes" class="form-horizontal group-border-dashed">
@endif 
    

    {{ csrf_field() }}

    <div class="form-group">
        <label class="col-sm-3 col-md-4 control-label">UUID</label>
        <div class="col-sm-6 col-lg-4">
            <input type="text" class="form-control input-sm text-center" value="1c0a1dfeffcbac416dd375e95c23ce6b" readonly="" />
        </div>
    </div>

    @if($shopBeacon->id != '')
        <input type='hidden' name='_method' value='PUT'>
        <input type="hidden" id="original_shop_id" value="{{ $shopBeacon->shop_id }}">
    @endif
    @if(isset($shop))
        <input type="hidden" name="shop_id"  value="{{  $shop->id }}">
    @else
        <div class="form-group">
            <label class="col-sm-3 col-md-4 control-label">{{ trans('models.shop') }}</label>
            <div class="col-sm-6 col-lg-4">
                <select name="shop_id" id="shop_id" class="form-control input-sm select2">
                    <option value="">Ninguno</option>
                        @foreach($shops as $shop)
                            <option value="{{ $shop->id }}" @if($shop->id ==  $shopBeacon->shop_id) selected="selected" @endif>{{ $shop->name }}</option>
                        @endforeach
                </select>
            </div>
        </div>
    @endif
    <input type="hidden" name="serial" id="serial" value="{{ old('serial',$shopBeacon->serial_string) }}">
    @if(\Auth::user()->type != 'seller')
        <div class="form-group">
            <label class="col-sm-3 col-md-4 control-label">Major</label>
            <div class="col-sm-6 col-lg-4">
                <input type="text" class="form-control input-sm text-center"  placeholder="Mayor"  required
                id="beacon-serial-mayor"
                data-parsley-pattern="[a-fA-F\d]{4}"
                data-parsley-minlength="4"
                data-parsley-maxlength="4"
                minlength="4"
                maxlength="4">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 col-md-4 control-label">Minor</label>
            <div class="col-sm-6 col-lg-4">
                <input type="text" class="form-control input-sm text-center"  placeholder="Minor" required
                id="beacon-serial-minor"
                data-parsley-pattern="[a-fA-F\d]{4}"
                data-parsley-minlength="4"
                data-parsley-maxlength="4"
                minlength="4"
                maxlength="4">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 col-md-4 control-label">{{ trans('data.description') }}</label>
            <div class="col-sm-6 col-lg-4">
                <textarea name="description" placeholder="{{ trans('placeholder.description') }}" class="form-control input-sm">{{ old('description',$shopBeacon->description) }}</textarea>
            </div>
        </div>


        <div class="form-group">
            <label class="col-sm-3 col-md-4 control-label">{{ trans('data.status') }}</label>
            <div class="col-sm-6 col-lg-4 xs-pt-5">
                <div class="switch-button switch-button-success" data-toggle="tooltip" title="{{$shopBeacon->id ? '' : 'No se puede activar antes de tener ofertas'}}">
                    <input type="checkbox" @if($shopBeacon->active) checked @endif name="active" {{$shopBeacon->id ? '' : 'disabled'}} id="swt5"><span>
                    <label for="swt5"></label></span>
                </div>
            </div>
        </div>
    @endif

    <div class="form-group">
        <div class="col-xs-12">
            <button type="submit" id="submit_button" class="btn btn-primary">
                @if($shopBeacon->id)
                    <span class="icon mdi mdi-edit"></span>
                    {{ trans('process.save') }}
                @else
                    <span class="glyphicon glyphicon-plus"></span>
                    {{ trans('process.create') }}
                @endif
            </button>
            <a href="{{ url('/beacons') }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>  {{ trans('process.back') }}</a>
        </div>
    </div>
</form>

resources/views/shopbeacon/header.blade.php
@section('containt-title'){{ trans('models.beacons') }} @endsection

@section('menu-beacons') class="active" @endsection

@section('breadcrumbs') 
    <li><a href="{{ url('beacons') }}" >{{ trans('models.list',['model'=>trans('models.beacons')] ) }}</a></li>
    @yield('product-breadcrumbs')
@endsection

resources/views/shopbeacon/index.blade.php
@extends('layouts.panel')

@section('content-panel') 

    @include('shopbeacon.header')
    @if(Auth::user()->type=="administrator")
    	<a href="{{ url('beacons/create') }}"  class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>  {{ trans('process.create') }}</a>
	@endif
	@include('shopbeacon.list')
    
@endsection
@section('footer')
    <script>$('#shopBeacons-datatable').DataTable({
            "pageLength": 100
        });</script>
@endsection

resources/views/shopbeacon/list.blade.php
@if(!isset($shopBeacons) && in_array(Auth::user()->type,['administrator','seller']))
    <a href="#shopbeacon-form" data-toggle="tab" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-plus"></span>  {{ trans('process.create') }} {{ trans('models.beacon') }}</a>
@endif
<hr/>
<table class="table table-striped table-condensed" id="shopBeacons-datatable">
    <thead>
        <tr>
            <th class="text-center">{{ trans('data.id')}}</th>
            @if(!isset($shop))
                <th>{{ trans('models.shop') }}</th>
            @endif
            <th>{{ trans('data.serial') }}</th>
            <th>{{ trans('data.description') }}</th>
            <th>{{ trans('data.offer-close') }}</th>
            <th>{{ trans('data.offer-far') }}</th>
            <th>{{ trans('data.action') }}</th>
        </tr>
    </thead>
    <tbody>
    @php $shopBeacons = isset($shopBeacons) ? $shopBeacons : $shop->beacons; @endphp

    @foreach ($shopBeacons  as $beacon)
        <tr @if(!$beacon->active) class="desactive" @endif>
            <td class="text-center">{{ str_limit($beacon->id,30) }}</td>
            @if(!isset($shop))
                <td>
                    @if ($beacon->shop)
                        {{ str_limit($beacon->shop->name,30) }}
                    @else
                        Ninguno
                    @endif
                </td>
            @endif
            <td>{{ $beacon->serial_string }}</td>
            <td>
                <span
                    @if(strlen($beacon->description) > 30)
                        data-toggle="tooltip" title="{{$beacon->description}}"
                    @endif
                >
                    {{ str_limit($beacon->description,30) }}
                </span>
            </td>
            <td>
                @if($beacon->products_around && $beacon->products_around->product_close)
                    <span
                        @if(strlen($beacon->products_around->product_close_message) > 35)
                            data-toggle="tooltip" title="{{$beacon->products_around->product_close_message}}"
                        @endif
                    >
                        {{ str_limit($beacon->products_around->product_close_message, 35)}}
                    </span>
                    <span class="label label-default"
                        @if(strlen($beacon->products_around->product_close->name) > 25)
                            data-toggle="tooltip" title="{{$beacon->products_around->product_close->name}}"
                        @endif
                    >
                        {{ str_limit($beacon->products_around->product_close->name, 25) }}
                    </span>
                @else
                    {{ trans('data.none') }}
                @endif
            </td>
            <td>
                @if($beacon->products_around && $beacon->products_around->product_far)
                    <span
                        @if(strlen($beacon->products_around->product_far_message) > 35)
                            data-toggle="tooltip" title="{{$beacon->products_around->product_far_message}}"
                        @endif
                    >
                        {{ str_limit($beacon->products_around->product_far_message, 35)}}
                    </span>
                    <span class="label label-default"
                        @if(strlen($beacon->products_around->product_far->name) > 25)
                            data-toggle="tooltip" title="{{$beacon->products_around->product_far->name}}"
                        @endif
                    >
                        {{ str_limit($beacon->products_around->product_far->name, 25) }}
                    </span>
                @else
                    {{ trans('data.none') }}
                @endif
            </td>
            <td>
                <form action='{{ url('beacons/'.$beacon->id) }}' method='POST' id="beacon-delete-{{ $beacon->id }}">
                    <input type="hidden" name="_method" value="DELETE">
                    {{ csrf_field()}}
                    @if(in_array(Auth::user()->type,['operator','administrator']))
                        @if ($beacon->shop)
                            <a class="icon mdi mdi-case btn btn-success" href="{{ url('products-beacon/'.$beacon->id) }}" data-toggle="tooltip" title="{{ trans("process.update").' '.trans("data.offer") }}"></a>
                        @endif
                    @endif
                    @if(in_array(Auth::user()->type,['seller']))
                        <a class="icon mdi mdi-edit btn btn-primary" href="{{ url('beacons/'.$beacon->id) }}" data-toggle="tooltip" title="{{ trans("process.update") }}"></a>
                    @endif
                    @if(in_array(Auth::user()->type,['administrator']))
                        <a class="icon mdi mdi-edit btn btn-primary" href="{{ url('beacons/'.$beacon->id) }}" data-toggle="tooltip" title="{{ trans("process.update") }}"></a>
                        <a data-modal="full-danger"  class="btn btn-danger md-trigger " onclick="formSelected='beacon-delete-{{ $beacon->id }}'" data-toggle="tooltip" title="{{ trans("process.delete") }}">
                            <span class="icon mdi mdi-delete"></span>
                        </a>
                    @endif
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/shopbeacon/products-beacon.blade.php
@extends('layouts.panel')

@section('product-breadcrumbs')
        <li><a href="{{ url('products-beacon/'.$shopBeacon->id) }}">{{ trans('process.update').' '.trans('data.offer') }}</a></li>
@endsection


@section('content-panel') 
    @include('shopbeacon.header')

    <form method="POST" role="form" class="form-horizontal group-border-dashed">
        <input type='hidden' name='_method' value='PUT'>
    {{ csrf_field() }}
        
    <legend>{{ trans('data.offer-close') }}</legend>
    <p>Será recibida por usuarios que se encuentren entre 0 y 5 de distancia del beacon</p>
    <input type='hidden' name='beacon_id' value='{{ $shopBeacon->id }}'>
    {{-- {{ $productsBeacon }} --}}
    <div class="form-group">
        <label class="col-sm-3 col-md-4 control-label">{{ trans('models.product') }}</label>
        <div class="col-sm-6 col-lg-4">        
            <select name="product_close_id"  class="form-control input-sm select2" required id="product_close">
                <option value="0" selected>{{ trans('data.none') }}</option>
                @foreach($products as $product)
                    <option value="{{ $product->id }}" @if($product->id ==  $productsBeacon->product_close_id) selected="selected" @endif>{{ $product->name }}</option>
                @endforeach
            </select>
            <span class="text-muted">{{ trans('data.offer-select') }}</span>
        </div>
    </div>
    <div class="form-group">
    <label class="col-sm-3 col-md-4 control-label">{{ trans('data.offer-message') }}</label>
        <div class="col-sm-6 col-lg-4">
            <input type="text" class="form-control input-sm"  name="product_close_message" placeholder="{{ trans('data.offer-add-message') }}" value="{{ old('product_close_message', $productsBeacon->product_close_message) }}" >
        </div>
    </div>
    <br/><br/>
    <legend>{{ trans('data.offer-far') }}</legend>
    <p>Será recibida por usuarios que se encuentren entre 6 y 30/40 de distancia del beacon</p>
    <div class="form-group">
        <label class="col-sm-3 col-md-4 control-label">{{ trans('models.product') }}</label>
        <div class="col-sm-6 col-lg-4">
            <select name="product_far_id" class="form-control input-sm select2" id="product_far" required data-parsley-offer>
                <option value="0" selected>{{ trans('data.none') }}</option>
                @foreach($products as $product)
                    <option value="{{ $product->id }}" @if($product->id ==  $productsBeacon->product_far_id) selected="selected" @endif>{{ $product->name }}</option>
                @endforeach
            </select>
            <span class="text-muted">{{ trans('data.offer-select') }}</span>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 col-md-4 control-label">{{ trans('data.offer-message') }}</label>
        <div class="col-sm-6 col-lg-4">
            <input type="text" class="form-control input-sm"  name="product_far_message" placeholder="{{ trans('data.offer-add-message') }}" value="{{ old('product_close_message', $productsBeacon->product_far_message) }}" >
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary"> @if($shopBeacon->id)<span class="icon mdi mdi-save"></span>  {{ trans('process.save') }} @else <span class="glyphicon glyphicon-plus"></span>  {{ trans('process.create') }}  @endif</button>
            <a href="{{ url('/beacons') }}" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span>  {{ trans('process.back') }}</a> 
        </div>
    </div>
</form>

@endsection

@section('footer')
    <script src="{{ URL::asset('js/products/productsbeacon.js') }}" type="text/javascript"></script>
@endsection

resources/views/shopbeacon/show.blade.php
@extends('layouts.panel')

@section('product-breadcrumbs')
    @if($shopBeacon->id)
        <li><a href="{{ url('beacons/'.$shopBeacon->id) }}">{{ trans('process.update') }}</a></li>
    @else
        <li><a href="{{ url('beacons/create') }}">{{ trans('process.create') }}</a></li>
    @endif
@endsection

@section('content-panel') 

    @include('shopbeacon.header')


    <div class="tab-content">
        <div class="tab-pane fade in active" id="shopBeacon-form">@include('shopbeacon.form')</div>
    </div>
@endsection

@section('footer')
    <script src="{{ URL::asset('js/shops/showProducts.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/loadAjaxForm.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('js/beacon/beacon-serial.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        $(window).bind("load", function() { 
            loadAjaxForm('form-productimage'); 
        });
    </script>
@endsection